<?php

declare(strict_types=1);

namespace App\Service;

class NameGeneratorService
{
    private const NATIONALITIES = [
        'English',
        'Spanish',
        'French',
        'German',
        'Brazilian',
        'Portuguese',
        'Nigerian',
        'Ghanaian',
        'Japanese',
        'South Korean',
        'Argentine',
        'Dutch',
        'Italian',
        'Swedish',
        'Danish',
        'Irish',
        'Ivorian',
        'Senegalese',
        'Chinese',
        'Polish',
    ];

    /**
     * Generate a simple full-name string (used for scouts, agents, coaches).
     * Brazilian players have a 20% chance of a mononym.
     */
    public function generateName(string $nationality): string
    {
        $pools = self::getNamePools();

        if (!isset($pools[$nationality])) {
            throw new \InvalidArgumentException("Unknown nationality: {$nationality}");
        }

        $pool      = $pools[$nationality];
        $firstName = $pool['firstNames'][array_rand($pool['firstNames'])];

        if ($nationality === 'Brazilian' && random_int(1, 5) === 1) {
            return $firstName;
        }

        $lastName = $pool['lastNames'][array_rand($pool['lastNames'])];

        return "{$firstName} {$lastName}";
    }

    /**
     * Generate a player name with cultural complexity, returned as separate parts.
     *
     * Rules applied in order:
     *  - Brazilian: 20% mononym (lastName = '')
     *  - Spanish / Portuguese / Brazilian / Argentine: 15% double-surname
     *  - All: 5% generational suffix appended to lastName
     *
     * @return array{firstName: string, lastName: string}
     */
    public function generatePlayerName(string $nationality): array
    {
        $pools = self::getNamePools();

        if (!isset($pools[$nationality])) {
            $nationality = 'English';
        }

        $pool      = $pools[$nationality];
        $firstName = $pool['firstNames'][array_rand($pool['firstNames'])];

        // Brazilian mononym (20%)
        if ($nationality === 'Brazilian' && random_int(1, 5) === 1) {
            return ['firstName' => $firstName, 'lastName' => ''];
        }

        $lastName = $pool['lastNames'][array_rand($pool['lastNames'])];

        // Double-surname for Iberian / Latin cultures (15%)
        $doubleSurnameNats = ['Spanish', 'Portuguese', 'Brazilian', 'Argentine'];
        if (in_array($nationality, $doubleSurnameNats, true) && random_int(1, 100) <= 15) {
            $second = $pool['lastNames'][array_rand($pool['lastNames'])];
            // Avoid identical pair
            $attempts = 0;
            while ($second === $lastName && $attempts < 5) {
                $second = $pool['lastNames'][array_rand($pool['lastNames'])];
                $attempts++;
            }
            $lastName = "{$lastName} {$second}";
        }

        // Generational suffix (5%)
        if (random_int(1, 100) <= 5) {
            $suffixes = match ($nationality) {
                'Brazilian', 'Portuguese' => ['Jr.', 'Filho', 'Neto'],
                'Spanish', 'Argentine'    => ['Jr.', 'II', 'III'],
                default                   => ['Jr.', 'II', 'III'],
            };
            $lastName .= ' ' . $suffixes[array_rand($suffixes)];
        }

        return ['firstName' => $firstName, 'lastName' => $lastName];
    }

    /**
     * Return a single first name for a given nationality (used for guardian generation).
     */
    public function generateFirstName(string $nationality): string
    {
        $pools = self::getNamePools();

        if (!isset($pools[$nationality])) {
            $nationality = 'English';
        }

        $pool = $pools[$nationality];
        return $pool['firstNames'][array_rand($pool['firstNames'])];
    }

    /**
     * Return a single last name for a given nationality.
     */
    public function generateLastName(string $nationality): string
    {
        $pools = self::getNamePools();

        if (!isset($pools[$nationality])) {
            $nationality = 'English';
        }

        $pool = $pools[$nationality];
        return $pool['lastNames'][array_rand($pool['lastNames'])];
    }

    public function getRandomNationality(): string
    {
        return self::NATIONALITIES[array_rand(self::NATIONALITIES)];
    }

    private static function getNamePools(): array
    {
        return [

            // -----------------------------------------------------------------
            // English
            // -----------------------------------------------------------------
            'English' => [
                'firstNames' => [
                    // Original Male Names (25)
                    'Alistair',
                    'Callum',
                    'Ewan',
                    'Gideon',
                    'Jasper',
                    'Kieran',
                    'Milo',
                    'Oscar',
                    'Quentin',
                    'Silas',
                    'Victor',
                    'Arthur',
                    'Desmond',
                    'Franklin',
                    'Hugo',
                    'Jude',
                    'Leopold',
                    'Nathaniel',
                    'Phineas',
                    'Sebastian',
                    'Ulysses',
                    'Wyatt',
                    'Yorick',
                    'Barnaby',
                    'Hamish',

                    // New Classic & Traditional Male Names (40)
                    'Lawrence',
                    'Leonard',
                    'Leo',
                    'Lewis',
                    'Levi',
                    'Lincoln',
                    'Linus',
                    'Lucas',
                    'Lyle',
                    'Matthew',
                    'Maximillian',
                    'Michael',
                    'Miles',
                    'Neil',
                    'Nolan',
                    'Oliver',
                    'Otto',
                    'Owen',
                    'Paul',
                    'Perry',
                    'Pierce',
                    'Preston',
                    'Quincy',
                    'Robert',
                    'Ross',
                    'Russell',
                    'Samuel',
                    'Simon',
                    'Sinclair',
                    'Steven',
                    'Theodore',
                    'Thomas',
                    'Tobias',
                    'Tristan',
                    'Truman',
                    'Adam',
                    'Albert',
                    'Albie',
                    'Alexander',
                    'Alfie',

                    // New Strong & Vintage Male Names (45)
                    'Alfred',
                    'Archie',
                    'Benjamin',
                    'Bobby',
                    'Caleb',
                    'Charlie',
                    'Daniel',
                    'David',
                    'Edward',
                    'Elias',
                    'Elijah',
                    'Elliot',
                    'Ezra',
                    'Felix',
                    'Frankie',
                    'Frederick',
                    'Freddie',
                    'Gabriel',
                    'George',
                    'Harry',
                    'Henry',
                    'Isaac',
                    'Jack',
                    'Jacob',
                    'James',
                    'Joseph',
                    'Joshua',
                    'Liam',
                    'Louie',
                    'Louis',
                    'Max',
                    'Noah',
                    'Ralph',
                    'Reggie',
                    'Reuben',
                    'Ronnie',
                    'Rory',
                    'Rupert',
                    'Stanley',
                    'Teddy',
                    'Theo',
                    'Andrew',
                    'Brian',
                    'Christopher',
                    'Dominic',

                    // New Unique & Modern Male Names (40)
                    'Alaric',
                    'Cassian',
                    'Evander',
                    'Leif',
                    'Thayer',
                    'Caius',
                    'Ronan',
                    'Boaz',
                    'Soren',
                    'Elio',
                    'Ansel',
                    'Huxley',
                    'Quinlan',
                    'Torin',
                    'Bram',
                    'Elwood',
                    'Jett',
                    'Axel',
                    'Rafe',
                    'Maddox',
                    'Zayden',
                    'Knox',
                    'Crew',
                    'Wilder',
                    'Phoenix',
                    'Dash',
                    'Eric',
                    'Francis',
                    'Grant',
                    'Harrison',
                    'Ian',
                    'Julian',
                    'Kenneth',
                    'Logan',
                    'Mark',
                    'Nicholas',
                    'Patrick',
                    'Ryan',
                    'Stephen',
                    'William'
                ],
                'lastNames' => [
                    // Original Surnames (50)
                    'Thorne',
                    'Sterling',
                    'Huxley',
                    'Beaumont',
                    'Blackwood',
                    'Whittaker',
                    'Sinclair',
                    'Graves',
                    'Pemberton',
                    'Ashworth',
                    'Gable',
                    'Hawthorn',
                    'Kensington',
                    'Ledger',
                    'Prescott',
                    'Rhodes',
                    'Talbot',
                    'Vance',
                    'Winter',
                    'Yardley',
                    'Banks',
                    'Croft',
                    'Davenport',
                    'Ellwood',
                    'Finch',
                    'Grier',
                    'Holt',
                    'Ives',
                    'Jago',
                    'Kemp',
                    'Lowen',
                    'Mercer',
                    'Nash',
                    'Orton',
                    'Pike',
                    'Quirk',
                    'Royce',
                    'Stoker',
                    'Teale',
                    'Upton',
                    'Vane',
                    'Wild',
                    'Yates',
                    'Archer',
                    'Booth',
                    'Crane',
                    'Drake',
                    'Frost',
                    'Hyde',
                    'Moss',

                    // New Distinguished & Aristocratic Style (35)
                    'Amesbury',
                    'Beresford',
                    'Cavendish',
                    'Darcy',
                    'Etheridge',
                    'Fairfax',
                    'Gresham',
                    'Holloway',
                    'Kingsley',
                    'Langley',
                    'Montague',
                    'Neville',
                    'Osborne',
                    'Pembroke',
                    'Radcliffe',
                    'Stanhope',
                    'Tillinghast',
                    'Wentworth',
                    'Althorp',
                    'Brampton',
                    'Chastain',
                    'Devereux',
                    'Ellington',
                    'Fitzroy',
                    'Gainsborough',
                    'Harcourt',
                    'Lovelace',
                    'Marchant',
                    'Northumberland',
                    'Oakhaven',
                    'Portman',
                    'Richmond',
                    'Stafford',
                    'Throckmorton',
                    'Wellington',

                    // New Nature & Locational English Names (35)
                    'Beckett',
                    'Clayton',
                    'Dalton',
                    'Easton',
                    'Fletcher',
                    'Granger',
                    'Heath',
                    'Irving',
                    'Jarvis',
                    'Knowles',
                    'Leighton',
                    'Marlowe',
                    'Norris',
                    'Oakley',
                    'Parkinson',
                    'Ridley',
                    'Sutton',
                    'Thorpe',
                    'Underwood',
                    'Vaughan',
                    'Weston',
                    'Barlow',
                    'Brooks',
                    'Clifford',
                    'Dale',
                    'Fenwick',
                    'Gardner',
                    'Hart',
                    'Keats',
                    'Lincoln',
                    'Meadowes',
                    'Palmer',
                    'Reed',
                    'Sawyer',
                    'Townsend',

                    // New Classic Occupational & Strong English Surnames (30)
                    'Adler',
                    'Baxter',
                    'Cartwright',
                    'Dexter',
                    'Everett',
                    'Foster',
                    'Glover',
                    'Hammond',
                    'Judas',
                    'Knight',
                    'Lister',
                    'Mason',
                    'Naylor',
                    'Page',
                    'Roper',
                    'Sloane',
                    'Tanner',
                    'Vatcher',
                    'Webb',
                    'Abbott',
                    'Ballard',
                    'Collier',
                    'Drummond',
                    'Fisher',
                    'Gregory',
                    'Horton',
                    'Miller',
                    'Reeve',
                    'Swift',
                    'Thatcher'
                ]
            ],

            // -----------------------------------------------------------------
            // Spanish
            // -----------------------------------------------------------------
            'Spanish' => [
                'firstNames' => [
                    // Original Male Names (25 retained, female names removed)
                    'Mateo',
                    'Joaquín',
                    'Thiago',
                    'Bruno',
                    'Gael',
                    'Iker',
                    'Santiago',
                    'Fermín',
                    'Rodrigo',
                    'Álvaro',
                    'Rafael',
                    'Matías',
                    'Esteban',
                    'Hugo',
                    'Javier',
                    'Alonso',
                    'Pascual',
                    'Ignacio',
                    'Diego',
                    'Francisco',
                    'Manuel',
                    'Alejandro',
                    'Felipe',
                    'Vicente',
                    'Enrique',

                    // New Traditional & Strong Male Names (45)
                    'Adrián',
                    'Agustín',
                    'Alberto',
                    'Andrés',
                    'Antonio',
                    'Arturo',
                    'Bernardo',
                    'Carlos',
                    'César',
                    'Cristóbal',
                    'Daniel',
                    'Darío',
                    'David',
                    'Eduardo',
                    'Emilio',
                    'Emanuel',
                    'Facundo',
                    'Federico',
                    'Fernando',
                    'Gerardo',
                    'Gonzalo',
                    'Gregorio',
                    'Guillermo',
                    'Gustavo',
                    'Hernán',
                    'Ismael',
                    'Jerónimo',
                    'Jorge',
                    'José',
                    'Juan',
                    'Julián',
                    'Leonardo',
                    'Lorenzo',
                    'Lucas',
                    'Luis',
                    'Marcos',
                    'Mariano',
                    'Mario',
                    'Miguel',
                    'Nicolás',
                    'Óscar',
                    'Pablo',
                    'Pedro',
                    'Ramón',
                    'Raúl',

                    // New Modern & Distinctive Male Names (40)
                    'Aarón',
                    'Adolfo',
                    'Alejo',
                    'Amadeo',
                    'Bautista',
                    'Beltrán',
                    'Camilo',
                    'Dante',
                    'Eneko',
                    'Enzo',
                    'Ezequiel',
                    'Fabio',
                    'Fausto',
                    'Gaspar',
                    'Ibai',
                    'Izán',
                    'Jacobo',
                    'Jonay',
                    'Lázaro',
                    'Leandro',
                    'Leonel',
                    'Lisandro',
                    'Lope',
                    'Luciano',
                    'Manolo',
                    'Marco',
                    'Mauricio',
                    'Maximiliano',
                    'Naim',
                    'Nico',
                    'Oliver',
                    'Orlando',
                    'Pelayo',
                    'Ramiro',
                    'Renato',
                    'Salvador',
                    'Saúl',
                    'Sebastián',
                    'Tomás',
                    'Valentín',

                    // Additional Regional & Classic Male Names (40)
                    'Aitor',
                    'Alfonso',
                    'Amando',
                    'Asier',
                    'Aurelio',
                    'Berto',
                    'Blas',
                    'Borja',
                    'Carmelo',
                    'Chema',
                    'Curro',
                    'Dionisio',
                    'Domingo',
                    'Eloy',
                    'Emiliano',
                    'Ernesto',
                    'Eusebio',
                    'Faustino',
                    'Feliciano',
                    'Flavio',
                    'Gervasio',
                    'Ginés',
                    'Heliodoro',
                    'Hilario',
                    'Isidro',
                    'Jacinto',
                    'Jenaro',
                    'Juanjo',
                    'Justo',
                    'Leopoldo',
                    'Modesto',
                    'Nacho',
                    'Narciso',
                    'Onofre',
                    'Paco',
                    'Pancho',
                    'Plácido',
                    'Quique',
                    'Ruperto',
                    'Teodoro'
                ],
                'lastNames' => [
                    // Original Surnames (50)
                    'Navarro',
                    'Villalobos',
                    'Montoya',
                    'Ferrán',
                    'Mendoza',
                    'Guerrero',
                    'Castillo',
                    'Fuentes',
                    'Delgado',
                    'Valdéz',
                    'Espinoza',
                    'Romero',
                    'Grijalva',
                    'Serrano',
                    'Pizarro',
                    'Vega',
                    'Ortega',
                    'Méndez',
                    'Cortés',
                    'Salazar',
                    'Guzmán',
                    'Beltrán',
                    'Benítez',
                    'Cabrera',
                    'Maldonado',
                    'Ibarra',
                    'Cisneros',
                    'Figueroa',
                    'Gallardo',
                    'Lozano',
                    'Miranda',
                    'Pacheco',
                    'Quintana',
                    'Roldán',
                    'Santillán',
                    'Trejo',
                    'Uribe',
                    'Vargas',
                    'Zúñiga',
                    'Paredes',
                    'Rosas',
                    'Gallegos',
                    'Arenas',
                    'Belmonte',
                    'Cárdenas',
                    'Dueñas',
                    'Estrada',
                    'Fajardo',
                    'Heredia',
                    'Jasso',

                    // New Common & Historical Surnames (50)
                    'García',
                    'Rodríguez',
                    'González',
                    'Fernández',
                    'López',
                    'Martínez',
                    'Sánchez',
                    'Pérez',
                    'Gómez',
                    'Martín',
                    'Jiménez',
                    'Ruiz',
                    'Hernández',
                    'Díaz',
                    'Moreno',
                    'Álvarez',
                    'Muñoz',
                    'Romero',
                    'Alonso',
                    'Gutiérrez',
                    'Torres',
                    'Domínguez',
                    'Vázquez',
                    'Ramos',
                    'Gil',
                    'Ramírez',
                    'Blanco',
                    'Molina',
                    'Morales',
                    'Suárez',
                    'Ortega',
                    'Delgado',
                    'Castro',
                    'Ortiz',
                    'Rubio',
                    'Marín',
                    'Sanz',
                    'Núñez',
                    'Iglesias',
                    'Medina',
                    'Garrido',
                    'Santos',
                    'Castillo',
                    'Cortes',
                    'Lozano',
                    'Cano',
                    'Prieto',
                    'Méndez',
                    'Cruz',
                    'Calvo',

                    // New Noble & Regional Surnames (50)
                    'Aguilar',
                    'Aranda',
                    'Barrios',
                    'Bravo',
                    'Caballero',
                    'Calderón',
                    'Campos',
                    'Carmona',
                    'Carrasco',
                    'Casado',
                    'Chávez',
                    'Cordero',
                    'Cuellar',
                    'Durán',
                    'Echeverría',
                    'Escudero',
                    'Ferrer',
                    'Franco',
                    'Fuentes',
                    'Guerra',
                    'Hidalgo',
                    'Huerta',
                    'Ibáñez',
                    'Jurado',
                    'Lara',
                    'León',
                    'Linares',
                    'Márquez',
                    'Montero',
                    'Mora',
                    'Ocaña',
                    'Olivares',
                    'Orozco',
                    'Palacios',
                    'Peña',
                    'Prado',
                    'Reyes',
                    'Rivas',
                    'Rivera',
                    'Sáenz',
                    'Salas',
                    'Segura',
                    'Sosa',
                    'Soto',
                    'Tejada',
                    'Toledo',
                    'Valenzuela',
                    'Velasco',
                    'Vera',
                    'Zamora'
                ],
            ],
            // -----------------------------------------------------------------
            // French
            // -----------------------------------------------------------------
            'French' => [
                'firstNames' => [
                    'Adrien',
                    'Cédric',
                    'Étienne',
                    'Gaël',
                    'Isidore',
                    'Loïc',
                    'Nicolas',
                    'Pascal',
                    'Rémy',
                    'Thierry',
                    'Yves',
                    'Bastien',
                    'Dorian',
                    'Fabien',
                    'Honoré',
                    'Jérôme',
                    'Maxime',
                    'Olivier',
                    'Rodolphe',
                    'Tanguy',
                    'Amaury',
                    'Corentin',
                    'Florent',
                    'Hugues',
                    'Matthieu',
                ],
                'lastNames' => [
                    'Lefebvre',
                    'Fontaine',
                    'Gauthier',
                    'Morel',
                    'Bernard',
                    'Petit',
                    'Durand',
                    'Leroy',
                    'Moreau',
                    'Simon',
                    'Laurent',
                    'Michel',
                    'Thomas',
                    'Robert',
                    'Richard',
                    'Dubois',
                    'Martin',
                    'Lambert',
                    'Masson',
                    'Girard',
                    'Roux',
                    'Vincent',
                    'Faure',
                    'Andre',
                    'Mercier',
                    'Blanc',
                    'Guerin',
                    'Boyer',
                    'Garnier',
                    'Chevalier',
                    'Legrand',
                    'Perron',
                    'Boucher',
                    'Renard',
                    'Giraud',
                    'Brun',
                    'Baron',
                    'Vidal',
                    'Dumas',
                    'Brunet',
                    'Roche',
                    'Adam',
                    'Leblanc',
                    'Dupont',
                    'Delacroix',
                    'Lemaire',
                    'Dumont',
                    'Lecomte',
                    'Rousseau',
                    'Le Goff',
                ],
            ],

            // -----------------------------------------------------------------
            // German
            // -----------------------------------------------------------------
            'German' => [
                'firstNames' => [
                    'Hans',
                    'Klaus',
                    'Friedrich',
                    'Helmut',
                    'Günter',
                    'Werner',
                    'Otto',
                    'Rudolf',
                    'Ernst',
                    'Hermann',
                    'Heinz',
                    'Franz',
                    'Wilhelm',
                    'Karl',
                    'Walter',
                    'Erich',
                    'Lukas',
                    'Felix',
                    'Jonas',
                    'Tim',
                    'Niklas',
                    'Tobias',
                    'Maximilian',
                    'Fabian',
                    'Sebastian',
                    'Stefan',
                ],
                'lastNames' => [
                    'Müller',
                    'Schmidt',
                    'Schneider',
                    'Fischer',
                    'Weber',
                    'Meyer',
                    'Wagner',
                    'Becker',
                    'Schulz',
                    'Hoffmann',
                    'Schäfer',
                    'Koch',
                    'Bauer',
                    'Richter',
                    'Klein',
                    'Wolf',
                    'Schröder',
                    'Neumann',
                    'Schwarz',
                    'Zimmermann',
                    'Braun',
                    'Krüger',
                    'Hofmann',
                    'Hartmann',
                    'Lange',
                    'Schmitt',
                    'Werner',
                    'Schmitz',
                    'Krause',
                    'Meier',
                    'Lehmann',
                    'Schmid',
                    'Schulze',
                    'Maier',
                    'Köhler',
                    'Herrmann',
                    'König',
                    'Walter',
                    'Mayer',
                    'Huber',
                    'Kaiser',
                    'Fuchs',
                    'Peters',
                    'Lang',
                    'Scholz',
                    'Möller',
                    'Weiß',
                    'Jung',
                    'Hahn',
                    'Schubert',
                    'Breitenberger',
                    'Schreiber',
                ],
            ],

            // -----------------------------------------------------------------
            // Brazilian
            // -----------------------------------------------------------------
            'Brazilian' => [
                'firstNames' => [
                    'Caio',
                    'Thiago',
                    'Murilo',
                    'Renato',
                    'Otávio',
                    'Heitor',
                    'Vinícius',
                    'Rodrigo',
                    'Marcelo',
                    'André',
                    'Douglas',
                    'Emerson',
                    'Fábio',
                    'Gustavo',
                    'Igor',
                    'Leandro',
                    'Maurício',
                    'Nelson',
                    'Paulo',
                    'Ricardo',
                    'Sérgio',
                    'Wagner',
                    'Cristiano',
                    'Eduardo',
                    'Henrique',
                ],
                'lastNames' => [
                    'Oliveira',
                    'Dos Santos',
                    'Pereira',
                    'Costa',
                    'Silva',
                    'Rodrigues',
                    'Almeida',
                    'Nascimento',
                    'Carvalho',
                    'Ferreira',
                    'Ribeiro',
                    'Sousa',
                    'Fernandes',
                    'Lima',
                    'Gomes',
                    'Marques',
                    'Rocha',
                    'Alves',
                    'Araújo',
                    'Castro',
                    'Barbosa',
                    'Machado',
                    'Cardoso',
                    'Teixeira',
                    'Cavalcante',
                    'Barros',
                    'Moraes',
                    'Viana',
                    'Freitas',
                    'Guimarães',
                    'Pires',
                    'Ramos',
                    'Monteiro',
                    'Correia',
                    'Mendes',
                    'Nunes',
                    'Lopes',
                    'Soares',
                    'Viegas',
                    'Tavares',
                    'Neves',
                    'Coelho',
                    'Cunha',
                    'Medeiros',
                    'Fonseca',
                    'Rezende',
                    'Bittencourt',
                    'Magalhães',
                    'Antunes',
                    'Dantas',
                ],
            ],

            // -----------------------------------------------------------------
            // Portuguese
            // -----------------------------------------------------------------
            'Portuguese' => [
                'firstNames' => [
                    'João',
                    'António',
                    'Manuel',
                    'Francisco',
                    'Pedro',
                    'Rui',
                    'Miguel',
                    'Luís',
                    'Carlos',
                    'Nuno',
                    'Diogo',
                    'Tiago',
                    'André',
                    'Gonçalo',
                    'Duarte',
                    'Afonso',
                    'Henrique',
                    'Ricardo',
                    'Bruno',
                    'Eduardo',
                    'Sérgio',
                    'Paulo',
                    'Rodrigo',
                    'Alexandre',
                    'Vasco',
                ],
                'lastNames' => [
                    'Azevedo',
                    'Figueiredo',
                    'Sequeira',
                    'Melo',
                    'Pacheco',
                    'Carvalho',
                    'Ferreira',
                    'Rodrigues',
                    'Costa',
                    'Pereira',
                    'Alves',
                    'Martins',
                    'Sousa',
                    'Santos',
                    'Gonçalves',
                    'Fernandes',
                    'Gomes',
                    'Ribeiro',
                    'Correia',
                    'Lopes',
                    'Nunes',
                    'Marques',
                    'Pinto',
                    'Teixeira',
                    'Cunha',
                    'Moreira',
                    'Coelho',
                    'Vieira',
                    'Faria',
                    'Borges',
                    'Machado',
                    'Monteiro',
                    'Nogueira',
                    'Cardoso',
                    'Pires',
                    'Amorim',
                    'Braga',
                    'Silveira',
                    'Guimarães',
                    'Tavares',
                    'Leal',
                    'Valente',
                    'Freitas',
                    'Brito',
                    'Mendes',
                    'Simões',
                    'Batista',
                    'Saraiva',
                    'Paiva',
                    'Salgado',
                ],
            ],

            // -----------------------------------------------------------------
            // Nigerian (Yoruba / Igbo / Hausa)
            // -----------------------------------------------------------------
            'Nigerian' => [
                'firstNames' => [
                    'Olumide',
                    'Babatunde',
                    'Chidi',
                    'Tayo',
                    'Olatunji',
                    'Femi',
                    'Kehinde',
                    'Taiwo',
                    'Adebayo',
                    'Afolabi',
                    'Akin',
                    'Biodun',
                    'Kola',
                    'Kunle',
                    'Niyi',
                    'Seun',
                    'Tobi',
                    'Tosin',
                    'Wale',
                    'Yemi',
                    'Emeka',
                    'Nnamdi',
                    'Obinna',
                    'Ugochukwu',
                    'Uchenna',
                    'Somto',
                    'Chijioke',
                    'Ekene',
                    'Aliyu',
                    'Aminu',
                    'Garba',
                    'Haruna',
                    'Ibrahim',
                    'Kabiru',
                    'Musa',
                    'Rabiu',
                    'Sani',
                    'Usman',
                    'Yusuf',
                    'Abubakar',
                    'Bello',
                ],
                'lastNames' => [
                    'Balogun',
                    'Okoro',
                    'Adeyemi',
                    'Eze',
                    'Okafor',
                    'Nwosu',
                    'Anyanwu',
                    'Igbokwe',
                    'Ajayi',
                    'Ajibade',
                    'Akinbiyi',
                    'Akinwale',
                    'Alabi',
                    'Ayoola',
                    'Ayodele',
                    'Bamidele',
                    'Bakare',
                    'Dike',
                    'Fashola',
                    'Idowu',
                    'Jegede',
                    'Lawal',
                    'Obafemi',
                    'Ogundele',
                    'Ogundimu',
                    'Ogunleye',
                    'Adesanya',
                    'Adewale',
                    'Adefope',
                    'Akintola',
                    'Awolowo',
                    'Agboola',
                    'Agoro',
                    'Chukwu',
                    'Ekwueme',
                    'Nweke',
                    'Obasi',
                    'Obi',
                    'Onwudiwe',
                    'Onyekachi',
                    'Okonkwo',
                    'Nnaji',
                    'Ikenna',
                    'Ifeanyi',
                    'Ezeji',
                    'Abubakar',
                    'Aliyu',
                    'Danladi',
                    'Musa',
                    'Shehu',
                    'Sulaiman',
                    'Umar',
                    'Yusuf',
                    'Badawi',
                    'Gwandu',
                ],
            ],

            // -----------------------------------------------------------------
            // Ghanaian (Akan / Twi day names + wider Ghanaian pool)
            // -----------------------------------------------------------------
            'Ghanaian' => [
                'firstNames' => [
                    'Kwame',
                    'Kofi',
                    'Kojo',
                    'Kwesi',
                    'Kwabena',
                    'Kweku',
                    'Yaw',
                    'Paa',
                    'Kow',
                    'Ebo',
                    'Nana',
                    'Fiifi',
                    'Dela',
                    'Elikem',
                    'Selorm',
                    'Selasi',
                    'Kafui',
                    'Eyram',
                    'Elom',
                    'Mawuli',
                    'Kwamena',
                    'Kodzo',
                    'Kekeli',
                    'Seli',
                    'Efo',
                    'Dedzo',
                    'Dodzi',
                    'Soso',
                    'Senanu',
                    'Kwamina',
                    'Kwesi',
                    'Ato',
                    'Atta',
                ],
                'lastNames' => [
                    'Mensah',
                    'Owusu',
                    'Asante',
                    'Boateng',
                    'Osei',
                    'Amponsah',
                    'Acheampong',
                    'Antwi',
                    'Amoah',
                    'Ofori',
                    'Asiedu',
                    'Appiah',
                    'Oteng',
                    'Quaye',
                    'Asamoah',
                    'Tetteh',
                    'Adjei',
                    'Sarfo',
                    'Opoku',
                    'Amankwah',
                    'Darko',
                    'Yeboah',
                    'Frimpong',
                    'Akoto',
                    'Aidoo',
                    'Bonsu',
                    'Afriyie',
                    'Nyarko',
                    'Poku',
                    'Anane',
                    'Barimah',
                    'Dankwa',
                    'Domfeh',
                    'Duah',
                    'Gyamfi',
                    'Kyei',
                    'Laryea',
                    'Mends',
                    'Nkrumah',
                    'Peprah',
                    'Quaicoe',
                    'Twum',
                    'Wiredu',
                    'Asumadu',
                    'Boadu',
                    'Ennin',
                    'Fordjour',
                    'Sarpong',
                    'Danso',
                    'Acheamfour',
                    'Asante-Mensah',
                    'Baidoo',
                ],
            ],

            // -----------------------------------------------------------------
            // Ivorian (French West African / Dioula / Baoulé)
            // -----------------------------------------------------------------
            'Ivorian' => [
                'firstNames' => [
                    'Abdoulaye',
                    'Adama',
                    'Alexis',
                    'Amara',
                    'Apollinaire',
                    'Arsène',
                    'Barthélémy',
                    'Clément',
                    'Daouda',
                    'Drissa',
                    'Edmond',
                    'Emmanuel',
                    'Fernand',
                    'Firmin',
                    'Florentin',
                    'Gilles',
                    'Habib',
                    'Inza',
                    'Jean-Baptiste',
                    'Joseph',
                    'Julien',
                    'Koffi',
                    'Ladji',
                    'Mamadou',
                    'Marcel',
                    'Modeste',
                    'Moussa',
                    'Narcisse',
                    'Noël',
                    'Oumar',
                    'Pascal',
                    'Paulin',
                    'Philippe',
                    'Pierre',
                    'Raoul',
                    'Rodrigue',
                    'Romuald',
                    'Samuel',
                    'Sékou',
                    'Seydou',
                    'Souleymane',
                    'Théodore',
                    'Théophile',
                    'Wilfried',
                    'Yapi',
                    'Yacouba',
                    'Youssouf',
                    'Zié',
                    'Valéry',
                ],
                'lastNames' => [
                    'Diakité',
                    'Coulibaly',
                    'Koné',
                    'Sidibé',
                    'Ouattara',
                    'Sangaré',
                    'Sylla',
                    'Cissé',
                    'Camara',
                    'Bamba',
                    'Touré',
                    'Fofana',
                    'Konaté',
                    'Diabaté',
                    'Doumbia',
                    'Dembélé',
                    'Bah',
                    'Barry',
                    'Baldé',
                    'Kouyaté',
                    'Diané',
                    'N\'Guessan',
                    'Koffi',
                    'Yao',
                    'Kouassi',
                    'Kouadio',
                    'N\'Goran',
                    'N\'Zi',
                    'Assi',
                    'Brou',
                    'Kouakou',
                    'Amoikon',
                    'Djè',
                    'Gnaman',
                    'Guei',
                    'Kassi',
                    'Kramo',
                    'Ohouo',
                    'Sié',
                    'Tokpa',
                    'Gnahoré',
                    'Aka',
                    'Amon',
                    'Assoumou',
                    'Blé',
                    'Dadié',
                    'Dago',
                    'Djaha',
                    'Kpan',
                    'Lobé',
                    'Yoboué',
                    'Zoro',
                    'Zogbo',
                ],
            ],

            // -----------------------------------------------------------------
            // Senegalese (Wolof / French West African)
            // -----------------------------------------------------------------
            'Senegalese' => [
                'firstNames' => [
                    'Abdou',
                    'Abdoulaye',
                    'Alioune',
                    'Assane',
                    'Bamba',
                    'Boubacar',
                    'Cheikh',
                    'Daouda',
                    'Ibrahima',
                    'Ismaïla',
                    'Lamine',
                    'Mame',
                    'Mamadou',
                    'Mbaye',
                    'Modou',
                    'Moussa',
                    'Ndoye',
                    'Omar',
                    'Pape',
                    'Samba',
                    'Sané',
                    'Seydou',
                    'Souleymane',
                    'Thierno',
                    'Youssou',
                    'Amady',
                    'Elhadji',
                    'Mactar',
                    'Oumar',
                    'Racine',
                    'Tidiane',
                    'Malik',
                    'Bara',
                    'Babacar',
                ],
                'lastNames' => [
                    'Diallo',
                    'Keita',
                    'Traoré',
                    'Sow',
                    'N\'Diaye',
                    'Diop',
                    'Fall',
                    'Ba',
                    'Gueye',
                    'Sarr',
                    'Sy',
                    'Diouf',
                    'Faye',
                    'Wade',
                    'Mboup',
                    'Thiam',
                    'Ndour',
                    'Badji',
                    'Bassène',
                    'Coly',
                    'Dièye',
                    'Diagne',
                    'Diatta',
                    'Diédhiou',
                    'Diémé',
                    'Dramé',
                    'Faty',
                    'Gaye',
                    'Kanté',
                    'Manga',
                    'Mané',
                    'Mendy',
                    'Niang',
                    'Sambou',
                    'Séne',
                    'Sonko',
                    'Tendeng',
                    'Thiaw',
                    'Tounkara',
                    'Tine',
                    'Barry',
                    'Balde',
                    'Kouyaté',
                    'Diabaté',
                    'Konaté',
                    'Camara',
                    'Mbaye',
                    'Touré',
                    'Dème',
                    'Lô',
                    'Cissé',
                    'Kane',
                ],
            ],

            // -----------------------------------------------------------------
            // Japanese (romanised)
            // -----------------------------------------------------------------
            'Japanese' => [
                'firstNames' => [
                    'Kenji',
                    'Ren',
                    'Shouta',
                    'Hiroto',
                    'Daiki',
                    'Kaito',
                    'Ryouta',
                    'Sora',
                    'Takumi',
                    'Yuuma',
                    'Kazuki',
                    'Tsubasa',
                    'Riku',
                    'Shinnosuke',
                    'Yuki',
                    'Kouta',
                    'Hayato',
                    'Satoshi',
                    'Sosuke',
                    'Daisuke',
                    'Takeshi',
                    'Akira',
                    'Jiro',
                    'Ichiro',
                    'Taro',
                ],
                'lastNames' => [
                    'Sato',
                    'Tanaka',
                    'Nakamura',
                    'Watanabe',
                    'Takahashi',
                    'Ito',
                    'Kobayashi',
                    'Yamamoto',
                    'Kato',
                    'Yoshida',
                    'Yamada',
                    'Sasaki',
                    'Yamaguchi',
                    'Saito',
                    'Matsumoto',
                    'Inoue',
                    'Kimura',
                    'Hayashi',
                    'Shimizu',
                    'Yamazaki',
                    'Mori',
                    'Abe',
                    'Ikeda',
                    'Hashimoto',
                    'Yamashita',
                    'Ishikawa',
                    'Nakajima',
                    'Maeda',
                    'Fujita',
                    'Okada',
                    'Goto',
                    'Hasegawa',
                    'Murakami',
                    'Kondo',
                    'Ishii',
                    'Sakamoto',
                    'Endo',
                    'Aoki',
                    'Fujii',
                    'Nishimura',
                    'Ota',
                    'Masuda',
                    'Kaneko',
                    'Okamoto',
                    'Nakagawa',
                    'Miura',
                    'Hara',
                    'Nakano',
                    'Ogawa',
                    'Ueda',
                ],
            ],

            // -----------------------------------------------------------------
            // South Korean (romanised)
            // -----------------------------------------------------------------
            'South Korean' => [
                'firstNames' => [
                    'Minho',
                    'Seunghyun',
                    'Donghyun',
                    'Jungkook',
                    'Taehyung',
                    'Namjoon',
                    'Junhoe',
                    'Sungmin',
                    'Yongjun',
                    'Jiwon',
                    'Hyunjin',
                    'Jooheon',
                    'Kibum',
                    'Woohyun',
                    'Myungsoo',
                    'Sanghyun',
                    'Jihoon',
                    'Junyoung',
                    'Seokjin',
                    'Jinwoo',
                    'Yunho',
                    'Changsub',
                    'Hyunwoo',
                    'Jiho',
                    'Eunwoo',
                    'Wonho',
                    'Shownu',
                    'Kihyun',
                ],
                'lastNames' => [
                    'Kim',
                    'Lee',
                    'Park',
                    'Choi',
                    'Jung',
                    'Kang',
                    'Cho',
                    'Yoon',
                    'Lim',
                    'Han',
                    'Oh',
                    'Shin',
                    'Kwon',
                    'Jang',
                    'Yang',
                    'Hwang',
                    'Song',
                    'Hong',
                    'Ko',
                    'Moon',
                    'Son',
                    'Ahn',
                    'Baek',
                    'Noh',
                    'Sim',
                    'Jeon',
                    'Nam',
                    'Jeong',
                    'Seo',
                    'Im',
                    'Ryu',
                    'Ha',
                    'Yoo',
                    'Ma',
                    'Ku',
                    'Hyun',
                    'Pyo',
                    'Bae',
                    'Wi',
                    'Eom',
                    'Ok',
                    'Joo',
                    'Cha',
                    'Do',
                    'Min',
                    'Seok',
                    'Byun',
                    'Cheon',
                    'Tae',
                    'Goo',
                ],
            ],

            // -----------------------------------------------------------------
            // Argentine (Spanish + heavy Italian influence)
            // -----------------------------------------------------------------
            'Argentine' => [
                'firstNames' => [
                    'Matías',
                    'Agustín',
                    'Nicolás',
                    'Facundo',
                    'Santiago',
                    'Ezequiel',
                    'Leandro',
                    'Rodrigo',
                    'Sebastián',
                    'Germán',
                    'Gonzalo',
                    'Pablo',
                    'Diego',
                    'Fernando',
                    'Cristian',
                    'Andrés',
                    'Ramiro',
                    'Sergio',
                    'Julio',
                    'Esteban',
                    'Hernán',
                    'Ariel',
                    'Tomás',
                    'Juan',
                    'Maximiliano',
                ],
                'lastNames' => [
                    'Gómez',
                    'Rodríguez',
                    'Fernández',
                    'García',
                    'Pérez',
                    'Martínez',
                    'López',
                    'González',
                    'Sánchez',
                    'Romero',
                    'Torres',
                    'Flores',
                    'Álvarez',
                    'Díaz',
                    'Medina',
                    'Herrera',
                    'Suárez',
                    'Morales',
                    'Castro',
                    'Ruiz',
                    'Acosta',
                    'Vega',
                    'Ríos',
                    'Blanco',
                    'Cabral',
                    'Ferreyra',
                    'Quiroga',
                    'Villanueva',
                    'Sosa',
                    'Ibáñez',
                    'Rossi',
                    'Ferrari',
                    'Bianchi',
                    'Conti',
                    'Gallo',
                    'Romano',
                    'Esposito',
                    'Greco',
                    'Leone',
                    'De Luca',
                    'Palermo',
                    'Mancini',
                    'Bruno',
                    'Ricci',
                    'Marino',
                    'Lombardi',
                    'Russo',
                    'Colombo',
                    'Santoro',
                    'Montagna',
                ],
            ],

            // -----------------------------------------------------------------
            // Dutch
            // -----------------------------------------------------------------
            'Dutch' => [
                'firstNames' => [
                    'Bram',
                    'Thijs',
                    'Lars',
                    'Joost',
                    'Martijn',
                    'Pim',
                    'Willem',
                    'Gijs',
                    'Koen',
                    'Niels',
                    'Stijn',
                    'Bas',
                    'Jelle',
                    'Luuk',
                    'Pieter',
                    'Teun',
                    'Arjan',
                    'Dirk',
                    'Hans',
                    'Jan',
                    'Lodewijk',
                    'Onno',
                    'Rutger',
                    'Ties',
                    'Valentijn',
                ],
                'lastNames' => [
                    'van Dijk',
                    'de Vries',
                    'Janssen',
                    'Bakker',
                    'Visser',
                    'Smit',
                    'de Jong',
                    'Mulder',
                    'van den Berg',
                    'de Groot',
                    'Postma',
                    'Bos',
                    'Vos',
                    'Hendriks',
                    'Dekker',
                    'Lucas',
                    'van Loon',
                    'Meijer',
                    'de Wit',
                    'Willems',
                    'van Leeuwen',
                    'van de Ven',
                    'van Beek',
                    'Hermans',
                    'de Graaf',
                    'van der Meer',
                    'van der Linden',
                    'van Vliet',
                    'de Bruijn',
                    'van Doorn',
                    'Hofman',
                    'Molenaar',
                    'Sanders',
                    'de Klerk',
                    'Groen',
                    'de Vos',
                    'van Rijn',
                    'de Koning',
                    'Schouten',
                    'de Boer',
                    'van Pelt',
                    'van Dam',
                    'Jacobs',
                    'van Wijk',
                    'Post',
                    'van Egmond',
                    'de Ridder',
                    'Bosch',
                    'van Gastel',
                    'van der Berg',
                ],
            ],

            // -----------------------------------------------------------------
            // Italian
            // -----------------------------------------------------------------
            'Italian' => [
                'firstNames' => [
                    'Marco',
                    'Lorenzo',
                    'Andrea',
                    'Matteo',
                    'Alessandro',
                    'Francesco',
                    'Luca',
                    'Giovanni',
                    'Roberto',
                    'Antonio',
                    'Stefano',
                    'Paolo',
                    'Mario',
                    'Giorgio',
                    'Luigi',
                    'Carlo',
                    'Giuseppe',
                    'Alberto',
                    'Riccardo',
                    'Davide',
                    'Nicola',
                    'Fabio',
                    'Massimo',
                    'Emanuele',
                    'Claudio',
                ],
                'lastNames' => [
                    'Rossi',
                    'Russo',
                    'Ferrari',
                    'Esposito',
                    'Bianchi',
                    'Romano',
                    'Colombo',
                    'Ricci',
                    'Marino',
                    'Greco',
                    'Bruno',
                    'Gallo',
                    'Conti',
                    'De Luca',
                    'Costa',
                    'Giordano',
                    'Mancini',
                    'Leone',
                    'Barbieri',
                    'Martini',
                    'Fontana',
                    'Mariani',
                    'Ferretti',
                    'Rinaldi',
                    'Caruso',
                    'Ferrero',
                    'Pellegrini',
                    'Palermo',
                    'Sergi',
                    'Lombardi',
                    'Moretti',
                    'Galli',
                    'Giuliani',
                    'Villa',
                    'De Santis',
                    'Bernardi',
                    'Sala',
                    'Sanna',
                    'Cattaneo',
                    'Parisi',
                    'De Angelis',
                    'Bianco',
                    'Fiore',
                    'Fabbri',
                    'Valentini',
                    'Orlando',
                    'Monti',
                    'Vitale',
                    'Marchetti',
                    'Calabrese',
                ],
            ],

            // -----------------------------------------------------------------
            // Swedish
            // -----------------------------------------------------------------
            'Swedish' => [
                'firstNames' => [
                    'Erik',
                    'Lars',
                    'Karl',
                    'Gunnar',
                    'Johan',
                    'Per',
                    'Anders',
                    'Björn',
                    'Jan',
                    'Magnus',
                    'Sven',
                    'Peter',
                    'Mikael',
                    'Thomas',
                    'Daniel',
                    'Fredrik',
                    'Jonas',
                    'Andreas',
                    'Martin',
                    'Mattias',
                    'Henrik',
                    'David',
                    'Niklas',
                    'Emil',
                    'Oscar',
                ],
                'lastNames' => [
                    'Johansson',
                    'Andersson',
                    'Karlsson',
                    'Nilsson',
                    'Eriksson',
                    'Larsson',
                    'Olsson',
                    'Persson',
                    'Svensson',
                    'Gustafsson',
                    'Pettersson',
                    'Jonsson',
                    'Jansson',
                    'Hansson',
                    'Bengtsson',
                    'Jönsson',
                    'Lindberg',
                    'Jacobsson',
                    'Magnusson',
                    'Lindström',
                    'Lindqvist',
                    'Lindgren',
                    'Berg',
                    'Axelsson',
                    'Bergström',
                    'Lundgren',
                    'Lund',
                    'Björk',
                    'Mattsson',
                    'Eklund',
                    'Lundin',
                    'Hedlund',
                    'Norberg',
                    'Strand',
                    'Lundqvist',
                    'Nyström',
                    'Holmberg',
                    'Sandström',
                    'Bergqvist',
                    'Holm',
                    'Henriksson',
                    'Sjöberg',
                    'Danielsson',
                    'Isaksson',
                    'Sundström',
                    'Claesson',
                    'Wallin',
                    'Engström',
                    'Löfgren',
                    'Björklund',
                ],
            ],

            // -----------------------------------------------------------------
            // Danish
            // -----------------------------------------------------------------
            'Danish' => [
                'firstNames' => [
                    'Lars',
                    'Søren',
                    'Jens',
                    'Thomas',
                    'Niels',
                    'Henrik',
                    'Michael',
                    'Peter',
                    'Jørgen',
                    'Jan',
                    'Per',
                    'Ole',
                    'Hans',
                    'Morten',
                    'Rasmus',
                    'Mikkel',
                    'Magnus',
                    'Bjarne',
                    'Carsten',
                    'Kristian',
                    'Frederik',
                    'Anders',
                    'Christian',
                    'Simon',
                    'Emil',
                ],
                'lastNames' => [
                    'Jensen',
                    'Nielsen',
                    'Hansen',
                    'Pedersen',
                    'Andersen',
                    'Christensen',
                    'Larsen',
                    'Sørensen',
                    'Rasmussen',
                    'Petersen',
                    'Jørgensen',
                    'Madsen',
                    'Kristensen',
                    'Olsen',
                    'Thomsen',
                    'Christiansen',
                    'Poulsen',
                    'Johansen',
                    'Knudsen',
                    'Mortensen',
                    'Møller',
                    'Jakobsen',
                    'Henriksen',
                    'Lund',
                    'Holm',
                    'Gregersen',
                    'Eriksen',
                    'Friis',
                    'Mikkelsen',
                    'Kjeldsen',
                    'Laursen',
                    'Dahl',
                    'Lindberg',
                    'Nygaard',
                    'Vestergaard',
                    'Berntsen',
                    'Clausen',
                    'Christoffersen',
                    'Riis',
                    'Kvist',
                    'Bech',
                    'Skov',
                    'Nissen',
                    'Frederiksen',
                    'Bendtsen',
                    'Jacobsen',
                    'Haas',
                    'Bang',
                    'Brøndum',
                    'Damgaard',
                ],
            ],

            // -----------------------------------------------------------------
            // Irish
            // -----------------------------------------------------------------
            'Irish' => [
                'firstNames' => [
                    'Ciarán',
                    'Oisín',
                    'Tadhg',
                    'Séamus',
                    'Pádraig',
                    'Cormac',
                    'Eoin',
                    'Rónán',
                    'Fionn',
                    'Cathal',
                    'Diarmuid',
                    'Fearghus',
                    'Cillian',
                    'Colm',
                    'Donncha',
                    'Ruairí',
                    'Conor',
                    'Liam',
                    'Seán',
                    'Declan',
                    'Brendan',
                    'Donal',
                    'Fergus',
                    'Patrick',
                    'Kevin',
                    'Páraic',
                ],
                'lastNames' => [
                    "O'Brien",
                    'Murphy',
                    'Kelly',
                    'Walsh',
                    "O'Sullivan",
                    'Smith',
                    "O'Connor",
                    'McCarthy',
                    'Byrne',
                    'Ryan',
                    "O'Neill",
                    'Doyle',
                    'Reilly',
                    'Sheehan',
                    'Quinn',
                    'Kavanagh',
                    'Lynch',
                    'Murray',
                    "O'Callaghan",
                    'McGuinness',
                    'Dunne',
                    'Moore',
                    'Gallagher',
                    "O'Rourke",
                    'Kennedy',
                    "O'Mahony",
                    'Nolan',
                    'Doherty',
                    'McGrath',
                    'Brennan',
                    'Flanagan',
                    'Madden',
                    'Connolly',
                    "O'Shea",
                    'Buckley',
                    'Barry',
                    'Keane',
                    'Coleman',
                    'Boyle',
                    'Burke',
                    'Collins',
                    'Cronin',
                    'Daly',
                    'Farrell',
                    'Fitzgerald',
                    'Fleming',
                    'Hogan',
                    'Keenan',
                    'Malone',
                    'MacCarthy',
                ],
            ],

            // -----------------------------------------------------------------
            // Chinese (romanised)
            // -----------------------------------------------------------------
            'Chinese' => [
                'firstNames' => [
                    'Wei',
                    'Zihan',
                    'Jun',
                    'Haoyu',
                    'Zihao',
                    'Yuze',
                    'Yuchen',
                    'Haoran',
                    'Zixuan',
                    'Yuxuan',
                    'Zichen',
                    'Jiahao',
                    'Mingze',
                    'Zitao',
                    'Tianyu',
                    'Peng',
                    'Fang',
                    'Bo',
                    'Cai',
                    'De',
                    'Enlai',
                    'Feng',
                    'Guang',
                    'Heng',
                    'Jian',
                    'Kun',
                    'Li',
                    'Min',
                    'Ning',
                    'Qiang',
                    'Rong',
                    'Sheng',
                    'Tao',
                    'Xian',
                    'Yang',
                ],
                'lastNames' => [
                    'Zhang',
                    'Chen',
                    'Huang',
                    'Zhao',
                    'Li',
                    'Wu',
                    'Liu',
                    'Yang',
                    'Zhou',
                    'Xu',
                    'Sun',
                    'Ma',
                    'Zhu',
                    'Hu',
                    'Guo',
                    'He',
                    'Gao',
                    'Lin',
                    'Luo',
                    'Liang',
                    'Song',
                    'Zheng',
                    'Xie',
                    'Han',
                    'Tang',
                    'Feng',
                    'Yu',
                    'Dong',
                    'Xiao',
                    'Cheng',
                    'Cao',
                    'Yuan',
                    'Deng',
                    'Fu',
                    'Shen',
                    'Zeng',
                    'Peng',
                    'Su',
                    'Lu',
                    'Jiang',
                    'Ye',
                    'Yan',
                    'Pan',
                    'Wei',
                    'Fan',
                    'Jin',
                    'Jia',
                    'Yao',
                    'Bai',
                    'Shao',
                ],
            ],

            // -----------------------------------------------------------------
            // Polish
            // -----------------------------------------------------------------
            'Polish' => [
                'firstNames' => [
                    'Kamil',
                    'Piotr',
                    'Marek',
                    'Tomasz',
                    'Krzysztof',
                    'Jakub',
                    'Michał',
                    'Rafał',
                    'Bartłomiej',
                    'Łukasz',
                    'Wojciech',
                    'Adam',
                    'Szymon',
                    'Jan',
                    'Paweł',
                    'Mateusz',
                    'Grzegorz',
                    'Dominik',
                    'Sebastian',
                    'Robert',
                    'Marcin',
                    'Maciej',
                    'Karol',
                    'Radosław',
                    'Filip',
                    'Przemysław',
                    'Dariusz',
                    'Artur',
                    'Tadeusz',
                    'Stanisław',
                ],
                'lastNames' => [
                    'Kowalski',
                    'Nowak',
                    'Wiśniewski',
                    'Wójcik',
                    'Kowalczyk',
                    'Kamiński',
                    'Lewandowski',
                    'Zieliński',
                    'Szymański',
                    'Woźniak',
                    'Dąbrowski',
                    'Kozłowski',
                    'Jankowski',
                    'Mazur',
                    'Kwiatkowski',
                    'Krawczyk',
                    'Piotrowski',
                    'Grabowski',
                    'Nowakowski',
                    'Pawlak',
                    'Michalski',
                    'Nowicki',
                    'Adamczyk',
                    'Dudek',
                    'Zając',
                    'Wieczorek',
                    'Jabłoński',
                    'Kaczmarek',
                    'Rutkowski',
                    'Ostrowski',
                    'Tomczak',
                    'Karpowicz',
                    'Baran',
                    'Wojtyla',
                    'Sikora',
                    'Walczak',
                    'Pietrzak',
                    'Głowacki',
                    'Krupa',
                    'Sobieraj',
                    'Witek',
                    'Czarnecki',
                    'Majewski',
                    'Olszewski',
                    'Wróbel',
                    'Borkowski',
                    'Stępień',
                    'Duda',
                    'Kubiak',
                    'Marciniak',
                ],
            ],

        ];
    }
}
