name: wunderkind-backend
recipe: symfony
config:
  php: '8.4'
  via: nginx
  webroot: public
  xdebug: false
  database: postgres:16

services:
  appserver_nginx:
    overrides:
      ports:
        - "127.0.0.1:52100:80"

  database:
    portforward: 5433
    creds:
      user: wunderkind
      password: wunderkind
      database: wunderkind

tooling:
  php:
    service: appserver
  composer:
    service: appserver
  symfony:
    service: appserver
    cmd: php bin/console
  psql:
    service: database
    cmd: psql -U wunderkind wunderkind
