<?php

namespace App\Controller\Admin;

use App\Entity\Competition\CompetitionRound;
use App\Enum\Competition\CompetitionRoundStatus;
use App\Enum\Competition\MatchEngineIdentifier;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Extension\Core\Type\EnumType;

/**
 * Read-only — rounds are generated by CompetitionLockService at instance-lock time and
 * progressed by CompetitionDrawService (draw phase) then CompetitionResultsService
 * (resolve phase), never hand-edited. Results/fixtures are surfaced via this detail
 * view's association list rather than standalone controllers, to avoid over-building
 * admin surface.
 */
class CompetitionRoundCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return CompetitionRound::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud->setDefaultSort(['scheduledAt' => 'ASC']);
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions->disable(Action::NEW, Action::EDIT, Action::DELETE);
    }

    public function configureFields(string $pageName): iterable
    {
        yield IdField::new('id')->hideOnForm();
        yield AssociationField::new('activeCompetition', 'Competition');
        yield IntegerField::new('roundIndex');
        yield TextField::new('label');

        yield ChoiceField::new('status')
            ->setFormType(EnumType::class)
            ->setFormTypeOptions(['class' => CompetitionRoundStatus::class]);

        yield ChoiceField::new('matchEngineIdentifier', 'Engine')
            ->setFormType(EnumType::class)
            ->setFormTypeOptions(['class' => MatchEngineIdentifier::class]);

        yield DateTimeField::new('scheduledAt', 'Draw due');
        yield DateTimeField::new('startedAt', 'Drawn at')->hideOnIndex();
        yield DateTimeField::new('matchesResolveAt', 'Resolve due')->hideOnIndex();
        yield DateTimeField::new('completedAt', 'Results published');
        yield DateTimeField::new('drawLockedAt')->hideOnIndex();
        yield DateTimeField::new('resolveLockedAt')->hideOnIndex();
    }
}
