<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260326000000BaselinePostgres extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE academy (id UUID NOT NULL, name VARCHAR(100) NOT NULL, reputation INT DEFAULT 0 NOT NULL, total_career_earnings BIGINT DEFAULT 0 NOT NULL, hall_of_fame_points INT DEFAULT 0 NOT NULL, last_synced_week INT DEFAULT 0 NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, market_pool_size INT DEFAULT 20 NOT NULL, financial_year_start SMALLINT DEFAULT 4 NOT NULL, country VARCHAR(2) DEFAULT NULL, pa_name VARCHAR(100) DEFAULT NULL, manager_temperament SMALLINT DEFAULT 50 NOT NULL, manager_discipline SMALLINT DEFAULT 50 NOT NULL, manager_ambition SMALLINT DEFAULT 50 NOT NULL, balance INT NOT NULL, manager_profile JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_994D0ECBA76ED395 ON academy (user_id)');
        $this->addSql('CREATE TABLE admin (id UUID NOT NULL, department VARCHAR(100) DEFAULT NULL, access_level INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_880E0D76A76ED395 ON admin (user_id)');
        $this->addSql('CREATE TABLE agent (id UUID NOT NULL, name VARCHAR(100) NOT NULL, reputation INT DEFAULT 50 NOT NULL, commission_rate NUMERIC(5, 2) NOT NULL, dob DATE DEFAULT NULL, nationality VARCHAR(60) DEFAULT NULL, judgements JSON NOT NULL, experience INT DEFAULT 0 NOT NULL, rating SMALLINT DEFAULT 50 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE facility (id UUID NOT NULL, type VARCHAR(255) NOT NULL, level SMALLINT DEFAULT 0 NOT NULL, last_upgraded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, academy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_105994B26D55ACAB ON facility (academy_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_105994B26D55ACAB8CDE5729 ON facility (academy_id, type)');
        $this->addSql('CREATE TABLE game_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, clique_relationship_threshold INT NOT NULL, clique_squad_cap_percent INT NOT NULL, clique_min_tenure_weeks INT NOT NULL, base_xp INT NOT NULL, base_injury_probability DOUBLE PRECISION NOT NULL, regression_upper_threshold INT NOT NULL, regression_lower_threshold INT NOT NULL, reputation_delta_base DOUBLE PRECISION NOT NULL, reputation_delta_facility_multiplier DOUBLE PRECISION NOT NULL, injury_minor_weight INT NOT NULL, injury_moderate_weight INT NOT NULL, injury_serious_weight INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE game_event_template (id UUID NOT NULL, slug VARCHAR(100) NOT NULL, category VARCHAR(30) NOT NULL, weight INT DEFAULT 1 NOT NULL, title VARCHAR(255) NOT NULL, body_template TEXT NOT NULL, impacts JSON NOT NULL, firing_conditions JSON DEFAULT NULL, severity VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B46AA1F989D9B62 ON game_event_template (slug)');
        $this->addSql('CREATE TABLE guardian (id UUID NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, gender VARCHAR(10) NOT NULL, date_of_birth DATE DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, demand_level SMALLINT DEFAULT 5 NOT NULL, loyalty_to_academy SMALLINT DEFAULT 50 NOT NULL, player_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6448605599E6F5DF ON guardian (player_id)');
        $this->addSql('CREATE TABLE inbox_message (id UUID NOT NULL, sender_type VARCHAR(255) NOT NULL, sender_name VARCHAR(150) NOT NULL, subject VARCHAR(255) NOT NULL, body TEXT NOT NULL, offer_data JSON DEFAULT NULL, status VARCHAR(255) DEFAULT \'unread\' NOT NULL, related_entity_type VARCHAR(100) DEFAULT NULL, related_entity_id VARCHAR(36) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, academy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_inbox_academy ON inbox_message (academy_id)');
        $this->addSql('CREATE TABLE investor (id UUID NOT NULL, company VARCHAR(150) NOT NULL, nationality VARCHAR(60) DEFAULT NULL, size VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tier VARCHAR(255) DEFAULT \'angel\' NOT NULL, investment_amount INT DEFAULT 0 NOT NULL, percentage_owned NUMERIC(5, 2) DEFAULT \'5.00\' NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, invested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_payout_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, academy_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BBAED266D55ACAB ON investor (academy_id)');
        $this->addSql('CREATE INDEX idx_investor_assigned_at ON investor (assigned_at)');
        $this->addSql('CREATE TABLE leaderboard_entry (id UUID NOT NULL, category VARCHAR(255) NOT NULL, score BIGINT DEFAULT 0 NOT NULL, period VARCHAR(20) NOT NULL, rank_position INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, academy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B08BDDB6D55ACAB ON leaderboard_entry (academy_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_leaderboard_academy_category_period ON leaderboard_entry (academy_id, category, period)');
        $this->addSql('CREATE TABLE player (id UUID NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, date_of_birth DATE NOT NULL, nationality VARCHAR(60) NOT NULL, position VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, recruitment_source VARCHAR(255) NOT NULL, potential SMALLINT NOT NULL, current_ability SMALLINT NOT NULL, contract_value INT DEFAULT 0 NOT NULL, pace SMALLINT DEFAULT 0 NOT NULL, technical SMALLINT DEFAULT 0 NOT NULL, vision SMALLINT DEFAULT 0 NOT NULL, power SMALLINT DEFAULT 0 NOT NULL, stamina SMALLINT DEFAULT 0 NOT NULL, heart SMALLINT DEFAULT 0 NOT NULL, height SMALLINT DEFAULT 0 NOT NULL, weight SMALLINT DEFAULT 0 NOT NULL, morale INT NOT NULL, age_out_warning_issued BOOLEAN DEFAULT false NOT NULL, forced_sale_executed BOOLEAN DEFAULT false NOT NULL, forced_sale_week INT DEFAULT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, personality_confidence SMALLINT DEFAULT 50 NOT NULL, personality_maturity SMALLINT DEFAULT 50 NOT NULL, personality_teamwork SMALLINT DEFAULT 50 NOT NULL, personality_leadership SMALLINT DEFAULT 50 NOT NULL, personality_ego SMALLINT DEFAULT 50 NOT NULL, personality_bravery SMALLINT DEFAULT 50 NOT NULL, personality_greed SMALLINT DEFAULT 50 NOT NULL, personality_loyalty SMALLINT DEFAULT 50 NOT NULL, academy_id UUID DEFAULT NULL, agent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A653414710B ON player (agent_id)');
        $this->addSql('CREATE INDEX idx_player_academy ON player (academy_id)');
        $this->addSql('CREATE INDEX idx_player_assigned_at ON player (assigned_at)');
        $this->addSql('CREATE TABLE player_siblings (player_source UUID NOT NULL, player_target UUID NOT NULL, PRIMARY KEY (player_source, player_target))');
        $this->addSql('CREATE INDEX IDX_A12DB694C08AE9AD ON player_siblings (player_source)');
        $this->addSql('CREATE INDEX IDX_A12DB694D96FB922 ON player_siblings (player_target)');
        $this->addSql('CREATE TABLE player_archetype (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, trait_mapping JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41D989DA5E237E06 ON player_archetype (name)');
        $this->addSql('CREATE TABLE scout (id UUID NOT NULL, name VARCHAR(100) NOT NULL, dob DATE DEFAULT NULL, nationality VARCHAR(60) DEFAULT NULL, judgements JSON NOT NULL, experience INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sponsor (id UUID NOT NULL, company VARCHAR(150) NOT NULL, nationality VARCHAR(60) DEFAULT NULL, size VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, monthly_payment INT DEFAULT 0 NOT NULL, contract_start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contract_end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reputation_min_threshold INT DEFAULT 0 NOT NULL, reputation_bonus_threshold INT DEFAULT NULL, bonus_multiplier NUMERIC(4, 2) DEFAULT \'1.00\' NOT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, early_termination_fee INT DEFAULT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_payment_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, academy_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_818CC9D46D55ACAB ON sponsor (academy_id)');
        $this->addSql('CREATE INDEX idx_sponsor_assigned_at ON sponsor (assigned_at)');
        $this->addSql('CREATE TABLE staff (id UUID NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, role VARCHAR(255) NOT NULL, coaching_ability SMALLINT DEFAULT 50 NOT NULL, scouting_range SMALLINT DEFAULT 50 NOT NULL, weekly_salary INT DEFAULT 0 NOT NULL, morale INT NOT NULL, specialty VARCHAR(50) DEFAULT NULL, specialisms JSON DEFAULT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dob DATE DEFAULT NULL, hired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, academy_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_staff_academy ON staff (academy_id)');
        $this->addSql('CREATE INDEX idx_staff_assigned_at ON staff (assigned_at)');
        $this->addSql('CREATE TABLE starter_config (id INT NOT NULL, starting_balance INT NOT NULL, starter_player_count INT NOT NULL, starter_coach_count INT NOT NULL, starter_scout_count INT NOT NULL, starter_sponsor_tier VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sync_record (id UUID NOT NULL, client_week_number INT NOT NULL, client_timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, server_timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payload JSON NOT NULL, is_valid BOOLEAN NOT NULL, invalid_reason VARCHAR(255) DEFAULT NULL, academy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33B5714E6D55ACAB ON sync_record (academy_id)');
        $this->addSql('CREATE TABLE transfer (id UUID NOT NULL, destination_club_name VARCHAR(100) NOT NULL, type VARCHAR(255) NOT NULL, fee INT DEFAULT 0 NOT NULL, agent_commission INT DEFAULT 0 NOT NULL, net_proceeds INT DEFAULT 0 NOT NULL, development_points INT DEFAULT 0 NOT NULL, reputation_gained INT DEFAULT 0 NOT NULL, buying_club VARCHAR(100) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, player_id UUID DEFAULT NULL, academy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4034A3C099E6F5DF ON transfer (player_id)');
        $this->addSql('CREATE INDEX IDX_4034A3C06D55ACAB ON transfer (academy_id)');
        $this->addSql('CREATE INDEX idx_transfer_academy_occurred ON transfer (academy_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_transfer_net_proceeds ON transfer (net_proceeds)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, manager_profile JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE academy ADD CONSTRAINT FK_994D0ECBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facility ADD CONSTRAINT FK_105994B26D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guardian ADD CONSTRAINT FK_6448605599E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_838936806D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investor ADD CONSTRAINT FK_8BBAED266D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE leaderboard_entry ADD CONSTRAINT FK_3B08BDDB6D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A656D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A653414710B FOREIGN KEY (agent_id) REFERENCES agent (id)');
        $this->addSql('ALTER TABLE player_siblings ADD CONSTRAINT FK_A12DB694C08AE9AD FOREIGN KEY (player_source) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE player_siblings ADD CONSTRAINT FK_A12DB694D96FB922 FOREIGN KEY (player_target) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sponsor ADD CONSTRAINT FK_818CC9D46D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE staff ADD CONSTRAINT FK_426EF3926D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sync_record ADD CONSTRAINT FK_33B5714E6D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C099E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C06D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE academy DROP CONSTRAINT FK_994D0ECBA76ED395');
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76A76ED395');
        $this->addSql('ALTER TABLE facility DROP CONSTRAINT FK_105994B26D55ACAB');
        $this->addSql('ALTER TABLE guardian DROP CONSTRAINT FK_6448605599E6F5DF');
        $this->addSql('ALTER TABLE inbox_message DROP CONSTRAINT FK_838936806D55ACAB');
        $this->addSql('ALTER TABLE investor DROP CONSTRAINT FK_8BBAED266D55ACAB');
        $this->addSql('ALTER TABLE leaderboard_entry DROP CONSTRAINT FK_3B08BDDB6D55ACAB');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A656D55ACAB');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A653414710B');
        $this->addSql('ALTER TABLE player_siblings DROP CONSTRAINT FK_A12DB694C08AE9AD');
        $this->addSql('ALTER TABLE player_siblings DROP CONSTRAINT FK_A12DB694D96FB922');
        $this->addSql('ALTER TABLE sponsor DROP CONSTRAINT FK_818CC9D46D55ACAB');
        $this->addSql('ALTER TABLE staff DROP CONSTRAINT FK_426EF3926D55ACAB');
        $this->addSql('ALTER TABLE sync_record DROP CONSTRAINT FK_33B5714E6D55ACAB');
        $this->addSql('ALTER TABLE transfer DROP CONSTRAINT FK_4034A3C099E6F5DF');
        $this->addSql('ALTER TABLE transfer DROP CONSTRAINT FK_4034A3C06D55ACAB');
        $this->addSql('DROP TABLE academy');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE facility');
        $this->addSql('DROP TABLE game_config');
        $this->addSql('DROP TABLE game_event_template');
        $this->addSql('DROP TABLE guardian');
        $this->addSql('DROP TABLE inbox_message');
        $this->addSql('DROP TABLE investor');
        $this->addSql('DROP TABLE leaderboard_entry');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE player_siblings');
        $this->addSql('DROP TABLE player_archetype');
        $this->addSql('DROP TABLE scout');
        $this->addSql('DROP TABLE sponsor');
        $this->addSql('DROP TABLE staff');
        $this->addSql('DROP TABLE starter_config');
        $this->addSql('DROP TABLE sync_record');
        $this->addSql('DROP TABLE transfer');
        $this->addSql('DROP TABLE "user"');
    }
}
