<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915213526 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add live_telemetry_snapshot for the landing page "Chairman\'s Terminal" widget';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE live_telemetry_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fixtures_simulated INT DEFAULT 0 NOT NULL, capital_deployed_pence BIGINT DEFAULT 0 NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE live_telemetry_snapshot');
    }
}
