<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds club_spotlight, the singleton cache row behind the landing page's
 * Club Spotlight feature (see App\Entity\ClubSpotlight / ClubSpotlightService).
 *
 * Hand-written rather than the raw doctrine:migrations:diff output: this dev
 * environment's schema had unrelated pre-existing drift against ORM metadata
 * (dropped defaults across game_config/pool_config/starter_config, and DROP
 * INDEX statements against the hand-maintained partial unique indexes CLAUDE.md
 * documents as not representable in ORM metadata) that diff would otherwise
 * have folded into this migration. None of that belongs here.
 */
final class Version20261006103425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add club_spotlight singleton table for the landing page Club Spotlight feature';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE club_spotlight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, club_name VARCHAR(100) NOT NULL, club_reputation BIGINT DEFAULT 0 NOT NULL, club_total_career_earnings BIGINT DEFAULT 0 NOT NULL, home_kit_config JSON DEFAULT NULL, away_kit_config JSON DEFAULT NULL, badge_config JSON DEFAULT NULL, owner_name VARCHAR(100) DEFAULT NULL, owner_nationality VARCHAR(100) DEFAULT NULL, owner_appearance JSON DEFAULT NULL, stadium_config JSON DEFAULT NULL, window_starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, window_ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE club_spotlight');
    }
}
