<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Replaces per-academy Facility rows with a global FacilityTemplate catalogue.
 *
 * Facilities are now template-driven: the backend defines the catalogue
 * (metadata, costs, decay config) and the frontend remains authoritative
 * for runtime state (levels, conditions). Templates are delivered to
 * clients via the sync response alongside gameConfig.
 */
final class Version20260412000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop facility table; create facility_template catalogue with 6 default templates';
    }

    public function up(Schema $schema): void
    {
        // Drop the old per-academy facility table
        $this->addSql('DROP TABLE IF EXISTS facility');

        // Create the global facility_template table
        $this->addSql('
            CREATE TABLE facility_template (
                id         UUID        NOT NULL PRIMARY KEY,
                slug       VARCHAR(60) NOT NULL,
                label      VARCHAR(100) NOT NULL,
                description TEXT       NOT NULL,
                category   VARCHAR(20) NOT NULL,
                base_cost  INTEGER     NOT NULL,
                weekly_upkeep_base INTEGER NOT NULL DEFAULT 0,
                reputation_bonus DOUBLE PRECISION NOT NULL DEFAULT 0,
                max_level  SMALLINT    NOT NULL DEFAULT 5,
                decay_base DOUBLE PRECISION NOT NULL DEFAULT 2,
                sort_order SMALLINT    NOT NULL DEFAULT 0,
                is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                CONSTRAINT uq_facility_template_slug UNIQUE (slug)
            )
        ');

        // Seed the 6 default facility templates.
        // baseCost in pence — frontend formula: (currentLevel + 1) × baseCost
        // weeklyUpkeepBase in pence — frontend formula: base × 1.5^level
        // UUIDs are generated by PostgreSQL via gen_random_uuid().
        $now = (new \DateTimeImmutable())->format('Y-m-d H:i:s');

        $templates = [
            ['technical_zone',  'Technical Zone',   'The heartbeat of your academy. Better facilities mean faster technical improvement.',                    'TRAINING', 500000,  500, 1.2, 5, 2.0, 1],
            ['strength_suite',  'Strength Suite',   'Dedicated gym and conditioning equipment for physical development.',                                     'TRAINING', 600000,  400, 0.8, 5, 2.0, 2],
            ['physio_clinic',   'Physio Clinic',    'State-of-the-art rehabilitation and injury prevention. Also expands squad capacity.',                    'MEDICAL',  800000,  600, 1.0, 5, 2.0, 3],
            ['hydro_pool',      'Hydro Pool',       'Hydrotherapy and recovery suite to get players back on their feet faster.',                              'MEDICAL',  900000,  700, 0.6, 5, 2.0, 4],
            ['tactical_room',   'Tactical Room',    'Video analysis and tactical boards to sharpen game intelligence.',                                       'SCOUTING', 700000,  350, 1.0, 5, 2.0, 5],
            ['scouting_center', 'Scouting Center',  'Talent identification hub that drives scouting intelligence and academy reputation.',                    'SCOUTING', 1000000, 300, 2.0, 5, 2.0, 6],
        ];

        foreach ($templates as [$slug, $label, $description, $category, $baseCost, $upkeep, $repBonus, $maxLevel, $decayBase, $sortOrder]) {
            $this->addSql(
                'INSERT INTO facility_template
                    (id, slug, label, description, category, base_cost, weekly_upkeep_base,
                     reputation_bonus, max_level, decay_base, sort_order, is_active, updated_at)
                 VALUES
                    (gen_random_uuid(), :slug, :label, :description, :category, :base_cost, :weekly_upkeep_base,
                     :reputation_bonus, :max_level, :decay_base, :sort_order, TRUE, :updated_at)',
                [
                    'slug'              => $slug,
                    'label'             => $label,
                    'description'       => $description,
                    'category'          => $category,
                    'base_cost'         => $baseCost,
                    'weekly_upkeep_base'=> $upkeep,
                    'reputation_bonus'  => $repBonus,
                    'max_level'         => $maxLevel,
                    'decay_base'        => $decayBase,
                    'sort_order'        => $sortOrder,
                    'updated_at'        => $now,
                ],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS facility_template');

        $this->addSql('
            CREATE TABLE facility (
                id               UUID        NOT NULL PRIMARY KEY,
                type             VARCHAR(255) NOT NULL,
                level            SMALLINT    NOT NULL DEFAULT 0,
                academy_id       UUID        NOT NULL,
                last_upgraded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
            )
        ');
    }

}
