<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the Languages & Translations schema: `language` (admin-configured languages),
 * `translation_key` (generic UI-copy keys and narrative-content field links), and
 * `translation` (one language's value for one key).
 *
 * `doctrine:migrations:diff` also picked up a large amount of unrelated local schema drift
 * (dropping partial unique indexes like uq_active_competition_one_open_per_template that are
 * intentionally raw-SQL-only and invisible to ORM metadata — see CLAUDE.md's "Key Gotchas" —
 * plus assorted game_config/pool_config column-default differences). None of that belongs in
 * this migration; it was stripped out by hand.
 */
final class Version20261003141339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add language, translation_key, and translation tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE language (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(5) NOT NULL, name VARCHAR(100) NOT NULL, is_enabled BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D4DB71B577153098 ON language (code)');
        $this->addSql('CREATE TABLE translation_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, entity_type VARCHAR(30) DEFAULT NULL, entity_slug VARCHAR(100) DEFAULT NULL, field_name VARCHAR(50) DEFAULT NULL, is_plural_sensitive BOOLEAN NOT NULL, banded_references JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AADCBD568A90ABA9 ON translation_key (key)');
        $this->addSql('CREATE UNIQUE INDEX uq_translation_key_entity_field ON translation_key (entity_type, entity_slug, field_name)');
        $this->addSql('CREATE TABLE translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value TEXT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, translation_key_id INT NOT NULL, language_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B469456FD07ED992 ON translation (translation_key_id)');
        $this->addSql('CREATE INDEX IDX_B469456F82F1BAF4 ON translation (language_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_translation_key_language ON translation (translation_key_id, language_id)');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456FD07ED992 FOREIGN KEY (translation_key_id) REFERENCES translation_key (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456F82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE translation DROP CONSTRAINT FK_B469456FD07ED992');
        $this->addSql('ALTER TABLE translation DROP CONSTRAINT FK_B469456F82F1BAF4');
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE translation_key');
        $this->addSql('DROP TABLE language');
    }
}
