<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds push-notification infrastructure: the `user_device` table (FCM registration tokens,
 * see UserDevice), the Symfony Messenger Doctrine transport's `messenger_messages` table
 * (async push dispatch, see PushNotificationService), and AdminMessage::sendAsPush/pushSentAt
 * (push as an additional delivery channel for admin-authored broadcasts).
 *
 * `doctrine:migrations:diff` also proposed the same unrelated pre-existing schema drift
 * (hand-added partial unique indexes, DROP DEFAULT/rename noise) documented in earlier
 * migrations in this file — none of that belongs here, so only the new tables/columns above
 * are kept.
 */
final class Version20260919211831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_device, messenger_messages, and AdminMessage sendAsPush/pushSentAt for push notifications';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_device (id UUID NOT NULL, device_token VARCHAR(4096) NOT NULL, platform VARCHAR(20) NOT NULL, device_id VARCHAR(255) DEFAULT NULL, last_active_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6C7DADB399B2415C ON user_device (device_token)');
        $this->addSql('CREATE INDEX idx_user_device_user ON user_device (user_id)');
        $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql('ALTER TABLE admin_message ADD send_as_push BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE admin_message ADD push_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_device DROP CONSTRAINT FK_6C7DADB3A76ED395');
        $this->addSql('DROP TABLE user_device');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE admin_message DROP send_as_push');
        $this->addSql('ALTER TABLE admin_message DROP push_sent_at');
    }
}
