<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add excursion table — bookable team events served to the app at GET /api/excursions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE excursion (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                slug VARCHAR(100) NOT NULL,
                title VARCHAR(150) NOT NULL,
                body TEXT NOT NULL,
                image_path VARCHAR(255) DEFAULT NULL,
                cost_per_person_pence INT DEFAULT 0 NOT NULL,
                effect_value INT DEFAULT 50 NOT NULL,
                negative_frequency INT DEFAULT 5 NOT NULL,
                target_audience VARCHAR(20) DEFAULT 'both' NOT NULL,
                post_season_only BOOLEAN DEFAULT false NOT NULL,
                cooldown_weeks INT DEFAULT 4 NOT NULL,
                active BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EXCURSION_SLUG ON excursion (slug)');
        // The API only ever serves active rows, cheapest first.
        $this->addSql('CREATE INDEX IDX_EXCURSION_ACTIVE_COST ON excursion (active, cost_per_person_pence)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE excursion');
    }
}
